### ISSUE TITLE
Scheduled posts for the WotD

### ISSUE THREAD

**Issue by DoodlePooge** [theothersophie/ASL-Assistant#1]
Hey friend!

I checked out the bot and your commands are clean, it's almost EXACTLY what I was looking for. Have you thought about setting up a way for an admin to schedule the WotD command in a channel at a time they set?

I was initially planning to make a bot myself, however, I figured I'd reach out first! I would be happy to collaborate too, or if you want to take the suggestion and run, that works too. :)

**Comment by theothersophie** [comment]
Hi! That repository is really outdated, im surprised its public.

Ive tried before but it only worked for a single server im in because I didnt want to overcomplicate  things or overload the tiny server its running on. It stopped working a while ago i dont remember why. People just do the command manually every day. If you would like the up to date code I can give it to you. I dont have time to maintain or expand it. I just do the bare minimum to keep it alive


________________________________
From: Paige Maute ***@***.***>
Sent: Monday, March 27, 2023 2:39:16 PM
To: theothersophie/ASL-Assistant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [theothersophie/ASL-Assistant] Scheduled posts for the WotD (Issue #1)


Hey friend!

I checked out the bot and your commands are clean, it's almost EXACTLY what I was looking for. Have you thought about setting up a way for an admin to schedule the WotD command in a channel at a time they set?

I was initially planning to make a bot myself, however, I figured I'd reach out first! I would be happy to collaborate too, or if you want to take the suggestion and run, that works too. :)

**Comment by DoodlePooge** [comment]
Whatever you think is best, there are some other things I would like to give a shot at and would appreciate anything you're willing to share. We'll see how far I make it lol

**Comment by theothersophie** [comment]
[asl-bot.zip](https://github.com/theothersophie/ASL-Assistant/files/11083711/asl-bot.zip)

I think this is everything, except of course i emptied the settings.py file with all my tokens and credentials. `dbl_token` isn't used anymore, idk what it is. `token` is the discord bot token and `DB_SETTINGS` are the database credentials needed to get random video urls. I could probably just give those credentials to you, its just an elephantsql account i dont use for anything else. Send me an email at sophiereddit@gmail.com if you want that

Also apologies in advance for this garbage code you might be better off writing it from scratch lol

**Comment by DoodlePooge** [comment]
Haha, not a problem at all. I was probably gonna go mostly from scratch. Again I appreciate it and I believe I'm in the bot support server and can communicate there on any questions or progress made.
